sudo: false
language: c
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.9
      - clang-3.6
      - m4
      - valgrind
env:
  - BUILD=Debug
  - BUILD=Release

before_script:
  - if [ "$CXX" = "clang" ]; then export CC="clang-3.6"; fi
  - make 

script:
  - make test
  - make valgrind

notifications:
  email: false

